version: '3.1'
services:
  jenkins:
    container_name: jenkins
    build:
      context: ./
      args:
        HOST_UID: ${HOST_UID}
        HOST_GID: ${HOST_GID}
    restart: unless-stopped
    volumes:
      - ${HOST_DOCKER}:/var/run/docker.sock
      - ${HOST_JENKINS_DATA}:/var/jenkins_home
    ports:
      - '${HOST_WWW}:8080'
      - '${HOST_OTHER}:50000'
volumes:
  jenkins_home:
